### ISSUE TITLE
Compaginar horarios del trabajo con el curso

### ISSUE THREAD

**Issue by RafaelAybar** [JJ/curso-tdd#165]
Hola @JJ , ¿se contempla el grabar las clases de Jitsi para que la gente que esté trabajando pueda verlas luego?

Entiendo que las prácticas a distancia están permitidas dada la situación actual, quizás habría que aclarar eso en el README.md

Un saludo.

**Comment by JJ** [comment]
Se tiene la intención, pero no sé si lo conseguiré...
