### ISSUE TITLE
Duda: cambio de proyecto

### ISSUE THREAD

**Issue by muetsii** [JJ/curso-tdd#256]
(perdona si abuso del sistema de issues, pero me pareció que es más ordenado y claro que preguntarlo por telegram)

Resulta que he empezado mis deberes con la aplicación de datos medioambientales. Lo escogí porque ahora mismo estoy trabajando con APIs REST, y me servía para usar mis conocimientos pero también coger más destreza empezando el proyecto de cero. Pero me encuentro finalmente un tanto desilusionado, por:

* En la fase de análisis vi que el tamaño para hacer algo medianamente útil es bastante grande, creé 5 hitos y muchas historias de usuario, sólo para tener algo que se pudiera usar. Y ni siquiera hemos empezado a programar.

* Pasé mucho tiempo buscando fuentes de datos, y veo también que es trabajoso adaptar y agregar cada fuente de datos.

* Otro alumno ha escogido el mismo proyecto.

* No me veo terminando esto, menos manteniéndolo.

* Encima mi proyecto está dando errores en los tests y creo que seguirá generando problemas.

Por otro lado, mientras añadía funcionalidad al proyecto, traté de incorporar un framework del que había oído hablar. Y encontré que no se adaptaba muy bien al problema de los datos medioambientales, PERO sin embargo iba muy bien para una vieja idea que nunca llegué a empezar por falta de conocimiento.

Esta nueva idea es una aplicación web, un chat con tiradas de dados para rol. A diferencia del otro:

* Gracias al framework, el tamaño de algo míniamente valioso es menor que lo de los datos medioambientales.

* Se trata de un ámbito que conozco bastante mejor.

* Tengo claro el diseño.

* Es algo que una vez estuviera hecho, yo mismo sería usuario.

* Me veo terminando al menos una versión usable y manteniéndola, por lo que hay contribución también a la sociedad (por los usuarios, y porque sería AGPL).

---
tl;dr;

* ¿Puedo cambiar de proyecto poniéndome al día con las tareas?

**Comment by JJ** [comment]
Claro que sí, pero recuerda que se testea por hitos. Puedes saltarte los,
pero se comprueban de todas formas

**Comment by muetsii** [comment]
Perfecto, muchísimas gracias.
