### ISSUE TITLE
404 en el link del hito 7

### ISSUE THREAD

**Issue by crisconru** [JJ/curso-tdd#488]
@JJ si le doy al link para ver que hace falta en el hito 7 -> [Gestor de tareas](https://jj.github.io/curso-tdd/temas/gestor-tareas#Actividad), me da un pete 404

**Comment by crisconru** [comment]
@crisconru @JJMerelo echale un ojo cuando puedas

**Comment by JJ** [comment]
Esto en el mensaje pineado, ¿no?
