### ISSUE TITLE
Como estudiante, sería interesante a nivel de UX tener un índice en el README

### ISSUE THREAD

**Issue by pablojj1808** [JJ/curso-tdd#534]
Permitiría ir a determinados puntos de forma mucho más _eficiente_ (parar el humano 😏).

**Comment by JJ** [comment]
Pero el índice [está](https://jj.github.io/curso-tdd#planificación-del-curso). Otra cosa es que no haya conseguido su objetivo puesto que no lo has visto. ¿Quieres decir que esté más visible?

**Comment by pablojj1808** [comment]
Algo como lo del **pr** (#535 ) propuesto sería muy útil para desplazarse por el readme rápidamente.

**Comment by pablojj1808** [comment]
Me refería a un índice del README no de los contenidos del curso, v.g. 
Planificación del curso
